### ISSUE TITLE
cannot connect wallet in brave browser

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#136]
When selecting metamask I get redirected to 

chrome-extension://agoakfejjabomempkjlepdflaleeobhb/home.html#/onboarding

![image](https://github.com/verity-team/dws/assets/367773/0761c1ff-0c45-43a0-957a-68c3fa12ef4c)

**Comment by al-maisan** [comment]
This works properly with the chrome browser

**Comment by GiveMeSomething** [comment]
@al-maisan I think Brave is trying to direct their user to use their own wallet. You can change it in the browser's settings.

https://github.com/brave/brave-browser/wiki/Wallet-support-FAQ#my-metamask-or-other-extension-is-not-working-with-dapps

The `Metamask` actually use the underlying `window.ethereum` object, which is injected to the browser by wallet provider (like Metamask, Brave Wallet, and the Core Wallet above)

**Comment by GiveMeSomething** [comment]
But Brave does provides their own wallet `Brave Wallet`. Not sure why the browser redirects you to the Core wallet site 👀

**Comment by al-maisan** [comment]
okay -- closing this
