### ISSUE TITLE
I get signed out in less than 5 minutes (should stay signed in for 24 hours?)

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#141]
IIUC I should stay signed in for a day -- when using https://truthmemes.io:8086/meme in the chrome browser I get signed out in less than 5 minutes though

![image](https://github.com/verity-team/dws/assets/367773/f560ea8e-e6bd-469d-b04a-c9d91fd91aa1)

**Comment by GiveMeSomething** [comment]
Maybe I have fixed this. Now account just need to reconnect to their wallet to be signed in (without having to sign a message).

Need further testing to see if this is working properly
