### ISSUE TITLE
user statistics popup: wrong etherscan URI for mainnet

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#165]
Please omit the `mainnet.` prefix  -- that fixes it.

`https://mainnet.etherscan.io/tx/0xa87b6e988527af214ed946aaeb141cc14377eb0125da5232cf9bd11b2bf66dba`

![image](https://github.com/verity-team/dws/assets/367773/b8fff788-5199-41d5-9c2a-f0792d36f188)

**Comment by alfydev** [comment]
The best would be to check in the code if the network nickname (defined as environment variable) is "mainnet", and to just omit it from the URL if it is. We need to keep the nickname in the URL when we're using sepolia or other testnets.

**Comment by al-maisan** [comment]
wontfix
