### ISSUE TITLE
The application thinks the wallet is connected when it's actually not: the application remembers a previous connection when it should not.

### ISSUE THREAD

**Issue by alfydev** [verity-team/dws#170]
If you connect your wallet, then close the browser completely, then open it again on the application, the application will believe the Metamask is already connected. However it is not: after closing and reopening the browser, it is necessary to re-authorize the connection in Metamask.

The application should check whether Metamask is *actually* and *properly* connected.
![bug](https://github.com/verity-team/dws/assets/117321123/53793b20-4f86-4232-a9b0-de230265d5aa)

**Comment by al-maisan** [comment]
which browser did you use?

**Comment by al-maisan** [comment]
I observe a similar error when I restart chrome - and click on the `Get $TRUTH` button without logging into `metamask` first.

![image](https://github.com/verity-team/dws/assets/367773/a3cc1a16-05e1-4bcc-aceb-f0a99f2a4710)

**Comment by al-maisan** [comment]
after I log in into `metamask` things work as expected

**Comment by alfydev** [comment]
The bug is exhibited for both in Firefox, Chromium and Brave. 

Note that I need to supply a password to Metamask before using it, if I haven't done so since the last time the browser was closed.

After shutting down the browser, the application should **not** assume the wallet is still connected. If the code is dealing with persistent connections using a cookie, it should be a session cookie (i.e. expires after browser shut down).

**Comment by GiveMeSomething** [comment]
Should be resolved by #171. Please redeploy and test it again.

@al-maisan @alfydev

**Comment by alfydev** [comment]
Indeed, it is fixed now.
