### ISSUE TITLE
[minor] The browser is warning that Lit is development mode, and that multiple versions are launched

### ISSUE THREAD

**Issue by alfydev** [verity-team/dws#180]
I get the warning that Lit is in dev mode both in the browser console, and in the shell output when launching the app.

`Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.`

Similarly I also get this:

`Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information.`

**Comment by al-maisan** [comment]
is this a potential security issue ?? if so, please fix asap
