### ISSUE TITLE
after a wallet connects do a POST on /wallet/connection

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#49]
related to #47 

if there was an affiliate code in the URL pass it on -- otherwise use the value `none`

see https://app.swaggerhub.com/apis/MUHAREM_1/delphi/1.0.0#/default/connectWallet for details

**Comment by al-maisan** [comment]
this still needs to be done

**Comment by GiveMeSomething** [comment]
Resolved with PR #74
