### ISSUE TITLE
pull user data every N seconds until the user has no unconformed transactions

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#75]
`M` and `N` should be configurable, maybe `M=5` and `N=60` is a good default?

1. POST /wallet/connection will return the user's donations -- if any has status "unconfirmed" keep calling GET /user/address/0xaddress every N seconds until they are all "confirmed"
2. when the user makes a donation: do the same thing
3. GET /user/address/0xaddress every `M` minutes just in case someone donated through a direct ETH transaction and not through the web app

IMPORTANT: display the total usd donated + tokens

**Comment by GiveMeSomething** [comment]
@al-maisan From what Al Fy said, should we always refresh the data every N seconds? I'm setting N as 120 seconds in the latest PR

p/s: The total donated stats is there, I just don't know where I should put it 😅

**Comment by al-maisan** [comment]
> @al-maisan From what Al Fy said, should we always refresh the data every N seconds? I'm setting N as 120 seconds in the latest PR
> 
> p/s: The total donated stats is there, I just don't know where I should put it 😅

I revised the description -- `M` and `N` should be configurable, maybe `M=5` and `N=60` is a good default?

**Comment by GiveMeSomething** [comment]
Okay, I'll try to reduce the refresh interval when there are `unconfirmed` transaction + when user just made the donation. Otherwise, the refresh interval is reverted to default value

These value can be configured in `.env` file.
