### ISSUE TITLE
user should be able to switch to a different ethereum account (connect/disconnect wallet?) 

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#77]
I may have one ethereum account where I just have ETH and another one where I keep tether.
In any case I should be able to switch to any ethereum account I control and make a donation using the funds in that account.

**Comment by GiveMeSomething** [comment]
Currently, there are no known ways to "truly" disconnect our site from wallet. I think this won't be updated in the near future because of security reasons (I think they don't want people/web-app tampering with user's trusted sites)

For now, they can switch between connected wallets when using our sites. If they want to add another wallet (or forgot to connect some), they will have to disconnect manually then connect again.

**Comment by GiveMeSomething** [comment]
Reference from `wagmi`, dependency of `walletconnect`. MetaMask and other injected providers [do not support programmatic disconnect](https://github.com/MetaMask/metamask-extension/issues/10353).

https://wagmi.sh/react/connectors/injected#shimdisconnect

**Comment by mohamadbastin** [comment]
> For now, they can switch between connected wallets when using our sites.

Hey there, 
do you mean users can switch between wallets manually? or that as developers we can switch between the user's connected wallet?
and if the latter, is there any documents on this?

**Comment by al-maisan** [comment]
> > For now, they can switch between connected wallets when using our sites.
> 
> Hey there, do you mean users can switch between wallets manually? or that as developers we can switch between the user's connected wallet? and if the latter, is there any documents on this?

When end users connect their wallet for the first time they can specify which ETH addresses (managed by the wallet) shall be included. After that the end users can switch between these addresses.

If they want to change the included addresses they need to disconnect the wallet from the web site altogether and repeat that procedure.

See e.g. https://help.1inch.io/en/articles/4666771-metamask-how-to-connect-disconnect-and-switch-accounts-with-metamask-on-1inch-network
